name: publish to nuget

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Build
        run: |
          dotnet build -c Release

      - name: Generate nuget package
        run: dotnet pack MarathonRunner.Console -c Release /p:Version=${VERSION} -o .

      - name: Push nuget package
        run: |
          dotnet nuget push "*.nupkg" --api-key ${{secrets.PACKAGES_PAT}} \
          --source https://nuget.pkg.github.com/terry-u16/index.json